### ISSUE TITLE
Block explorer issue

### ISSUE THREAD

**Issue by bizzyvinci** [bizzyvinci/moonriver-unified-subquery#5]
Some issues were noticed when using this subquery for [moonriver block explorer](https://github.com/bizzyvinci/moonriver-explorer) and would need to be rectified in the next release.

- [x] Account id has not been fully unified. Some use lowercase and others combine lower and upper cases. All addresses should use lowercase
- [ ] Account freeBalance, reservedBalance and totalBalance is not correct. Some have negative freeBalance (This would be resolved from the frontend)

**Comment by jamesbayly** [comment]
In terms of balance, keeping track of amounts purely through events is difficult. We have found it safer to do an RPC call for final balance after every event that might affect the balance

**Comment by bizzyvinci** [comment]
Right. That's what I have in mind. I'll use [polkadot rpc](https://polkadot.js.org/docs/substrate/rpc/#getbalanceaddress-h160-number-blocknumber-u256). But I don't know if EVM balance such as ERC20 and ERC721 is included, would test it out.

**Comment by jamesbayly** [comment]
@bizzyvinci you can use direct RPC calls for Eth balance on Moonbeam https://docs.moonbeam.network/builders/get-started/eth-compare/rpc-support/
